### ISSUE TITLE
推送通知经常会卡住

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#100]
celery在运行一段时间后会卡住，不再处理任务，导致推送等功能失效。此时可以重启以暂时解决此问题。

具体复现方法咱不明确。此问题严重影响后端功能性，请研究。

**Comment by hasbai** [comment]
尝试修复 [7a44f9e](https://github.com/OpenTreeHole/backend/commit/7a44f9e3ef83c193aa426ade8fca1d435ae64264)
