### ISSUE TITLE
No protect for dev branch?

### ISSUE THREAD

**Issue by w568w** [OpenTreeHole/backend#106]
Dev branch is for development purposes. And our team is too small for reviewing *every* little commits. It will slow down our active development.

We had better only protect `master` branch which is deployed to the production environment.

**Comment by hasbai** [comment]
考虑到新接触 django 的成员对框架API可能不太熟悉，如果直接提交代码可能会引发错误、造成不必要的性能开销或使代码复杂难懂。因此仓库主管人员对代码进行审核和建议修改是有必要的，也能帮助新开发人员快速熟悉框架以及最佳实践。

**Comment by w568w** [comment]
> 考虑到新接触 django 的成员对框架API可能不太熟悉，如果直接提交代码可能会引发错误、造成不必要的性能开销或使代码复杂难懂。因此仓库主管人员对代码进行审核和建议修改是有必要的，也能帮助新开发人员快速熟悉框架以及最佳实践。

Then I am afraid that it would be better to give me an `only-read` permission of this repository. 

The `dev` branch means *develop* to me, so I assume that what you *really* wanna prevent is that **bad codes go into the *production* line** (not *dev* line!). 

Now the repo is blocking *nearly everything* from commiting into the dev branch directly, which looks not so good to me - **it is important to protect a branch if 100+ maintainers can commit, but it is strange to do that if there is only you and me contributing now.**

**Comment by hasbai** [comment]
你可以在新的分支上开发，并提交PR

**Comment by w568w** [comment]
> 你可以在新的分支上开发，并提交PR

So I opened a pull request https://github.com/OpenTreeHole/backend/pull/108  20 hours ago. No reviewers, no suggestions, nothing at all.

**Comment by hasbai** [comment]
不要高估我的效率——尤其是新游戏发售时。

**Comment by w568w** [comment]
😅
