### ISSUE TITLE
使用自定义 Auth User Model

### ISSUE THREAD

**Issue by kavinzhao** [OpenTreeHole/backend#11]
目前我们使用User Profile存储用户数据。这是旧版Django的推荐做法，现已不建议使用。

根据[Django文档](https://docs.djangoproject.com/zh-hans/3.2/topics/auth/customizing/#substituting-a-custom-user-model)：

> 如果你准备启动一个新的项目，强烈推荐你设置一个自定义的用户模型，即使默认的用户模型对你来说已经足够了。这个模型的行为与默认用户模型相通，但是你能在未来需要的时候自定义它

> 在你已经建立数据库表之后再去修改 AUTH_USER_MODEL 要困难的多，因为它会影响外键和多对多关系。

因此，建议将Django内置的`AUTH_USER_MODEL`替换为自定义模型，并加入用户数据的相关字段，而不是新开一个单独的Profile。这将使模型具有更强的可扩展性，并减少很多不必要的麻烦（例如User Profile不存在）等。

**Comment by hasbai** [comment]
已完成，相关 API 正在实现

**Comment by hasbai** [comment]
用户数据 API 已完成，OpenTreeHole/backend#6 可自行添加所需字段
