### ISSUE TITLE
Websocket 通知服务无法连接

### ISSUE THREAD

**Issue by dest1n1s** [OpenTreeHole/backend#110]
**Describe the bug**
无法连接wss://www.fduhole.com/ws/notification

**To Reproduce**
携带用户token尝试连接wss://www.fduhole.com/ws/notification

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/13075143/156366307-1d1d5610-1696-46b1-9359-a35cdb3ad144.png)

**Comment by hasbai** [comment]
好像是 /api/ws/notification
