### ISSUE TITLE
服务器安全

### ISSUE THREAD

**Issue by kavinzhao** [OpenTreeHole/backend#12]
考虑到Secrets、证书私钥和APNS key等敏感数据存储在生产服务器上，必须部署SELinux以严格控制敏感文件访问权限。

- [ ] 为Docker部署SELinux，（参考[这个](https://opensource.com/article/20/11/selinux-containers)？）
- [ ] 严格落实最小权限原则，确保所有暴露在互联网上的进程以低权限用户运行
- [ ] 安全审计机制？

具体细节可能需要进一步讨论，这个Issue先放在这里作为备忘录

**Comment by hasbai** [comment]
部署运维相关问题移至 deploy 仓库，详见 OpenTreeHole/deploy#1
