### ISSUE TITLE
Feature Request: 跨帖引用

### ISSUE THREAD

**Issue by kavinzhao** [OpenTreeHole/backend#13]
目前所使用的[reply_to]方式仅能引用同一楼层内的一个帖子，但有时会遇到需要跨贴引用的情况（e.g. 如何评价某贴中的某回复）

因此，可以考虑新增如下功能：
- [x] 支持跨帖引用
- [x] 支持引用多个帖子，并可以定义引用在文字中出现的位置

虽然引用主要是前端渲染的事情，但理想情况下服务器应当将被引用的内容随原内容一起传给前端，以减少请求次数。

**Comment by hasbai** [comment]
reply_to 从功能上来说是起“回复“的作用，是对帖子的直接回应，因而一条帖子只能回复一条，而你所提到的”引用“的功能可以认为是一种提及，与回复有所不同。因此可以另做打算，比如直接在文本中编码 #{id} 的形式，再由前端渲染成为链接或卡片

**Comment by kavinzhao** [comment]
虽然是这样，但实际上引用和回复在功能上会有重合之处，回复可以看作引用的真子集(?)

**Comment by hasbai** [comment]
可以把 reply_to 改为 mention 字段，映射到多个帖子

**Comment by hasbai** [comment]
已完成，reply_to 改为 mention 字段，是帖子 id 的数组，引用在文字中出现的位置编码在文本中，由前端渲染
