### ISSUE TITLE
隐藏已删除的课评

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#134]
![img_v3_029c_8e35e6c5-5948-44b6-964d-ec58f55d930g](https://github.com/OpenTreeHole/backend/assets/12184989/29d3bd69-bb6e-4e85-a428-6188c813f95d)

如图所示，已删除的内容占用较多空间，致使浏览效率低下且影响观感，因此不应返回给前端。

**Comment by JingYiJun** [comment]
原因是数据库中文本为已删除但是没有删除字段标记，已处理
