### ISSUE TITLE
开发/管理帖特殊标记

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#14]
为了更准确地识别开发团队和管理团队的公告帖子，应当允许为这些帖子添加一个标记。

此标记随`Floor`发送给前端，由前端渲染为一个特殊的tag（或者其他用户无法伪造的方式），以方便用户辨别。

此标记还可以用于标注因违规而删除的帖子，以防用户伪造"该内容因违反社区规范而删除"的整活文字。

**Comment by hasbai** [comment]
管理员可以修改前端显示的用户名 anonyname，可以解决这个问题
被删除的帖子有一个 deleted 字段，可由前端加样式来和正常帖子区分

**Comment by kavinzhao** [comment]
那么或许可以约定一个标记，例如anonyname = `__管理员__FDUHole管理团队`，前端将`__`之间的内容加样式特殊渲染
仅修改用户名可能不是很醒目？
