### ISSUE TITLE
CORS 错误

### ISSUE THREAD

**Issue by dest1n1s** [OpenTreeHole/backend#25]
**Describe the bug**
这几天在白天(约8:00~21:00)间HTTP请求hole.hath.top均会出现CORS 错误（跨域资源共享错误：PreflightMissingAllowOriginHeader），而在夜间基本上不会有此问题。

**To Reproduce**
在上述时间段请求任何hath.hole.top下的路径即可.

**Screenshots (Optional)**
![image](https://user-images.githubusercontent.com/13075143/140244801-f387dfb9-3244-4a36-9a06-13af8c96e2ad.png)

**Version**
dev-latest

**Comment by hasbai** [comment]
服务器崩溃了，正在寻找原因

**Comment by hasbai** [comment]
网络问题，已修复
