### ISSUE TITLE
mention应该由服务器根据帖子内容识别而非客户端提交

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#36]
否则可能会因客户端标准不统一/恶意传递错误信息导致数据不统一

**Comment by hasbai** [comment]
mention 为帖子 id 的数组，不存在标准不统一的问题

**Comment by singularity-s0** [comment]
此内容不应依赖于前端。为了数据完整性考虑，原则上应属于后端判断。

**Comment by hasbai** [comment]
为何会有数据完整性的问题？

**Comment by singularity-s0** [comment]
如果前端implementation不一致，或者有bug，或者有人抓包自己写了不符合规范的客户端，将导致后端数据不完整。后端不应依赖前端判断。

**Comment by hasbai** [comment]
1. 前端在需要 mention 的位置以 #{{floor_id}} 编码在正文中，并应将 id 加入 mention 字段中发送到后端。这一点目前 web 和 app 前端的实现是一致的，也已被加入 api 文档中
2. 前端的 bug 应当由前端负责
3. 使用不规范客户端的用户应当自己承担责任

**Comment by singularity-s0** [comment]
但现在的问题是这会影响后端数据，进而影响其他用户和整个系统
