### ISSUE TITLE
发送初始密码至用户邮箱

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#42]
要不然用户必忘

**Comment by hasbai** [comment]
用户应当自行设置密码，不建议前端随机设置密码，这会给用户“我的密码被人操控”的心理暗示。而且将明文密码发送邮件的做法没有先例，也不够安全，明文密码应当尽可能少地出现。
另外提出 issue 请遵照 issue 模板

**Comment by singularity-s0** [comment]
自行设置密码要求一步额外操作，不应该强制用户做这件事。

> 这会给用户“我的密码被人操控”的心理暗示

不太能理解，而且用户理应知道平台本来就可以修改用户密码

> 将明文密码发送邮件的做法没有先例

有部分服务在重置密码时会将生成的随机密码发送至邮箱。如果担心用户邮箱安全性不够，那么本来也可以通过邮箱重置密码，这种担心没有意义。

**Comment by hasbai** [comment]
1. 可以给用户选择是自行设置密码还是由应用程序随机生成密码
2. 只有在用户同意的情况下，平台才能修改密码
3. 如果是常用密码的话泄露后对用户的损害极大，不发送密码邮件则无这样的隐患

总之，用户拥有设置其密码的权利，也有记住其密码的义务，这个责任不应由我们来承担。

**Comment by singularity-s0** [comment]
1 可以
3 随机生成的密码不可能是常用密码，不会有隐患

理论上用户应该记住其密码，但实际上用户不会这么做，从用户体验的角度考虑应该由我们承担责任。
“你不能甩锅给用户”

**Comment by hasbai** [comment]
可行的方案是：后端开放邮件接口，前端仅在随机生成密码时调用该接口发送密码邮件
