### ISSUE TITLE
API KEY 生成机制

### ISSUE THREAD

**Issue by hasbai** [OpenTreeHole/backend#47]
**Is your feature request related to a problem? Please describe.**
API KEY 的生成机制迟迟没有提交，这是 APP 端认证用户的手段，属于最基本的功能，应当被优先解决。

**Describe the solution you'd like**
等待能否获得学校的oauth，在找到更好的认证方式之前，正式版将暂缓发布

**Describe alternatives you've considered**
1. 目前提到的基于时间生成令牌
    理由：由于种子需要被写进前端，无论算法是否开源，都有被反编译的可能
2. 将uis学号和密码发给后端，后端完成验证即可
    理由：后端可能被黑客植入后门截取所有凭据，可能触发UIS风控

**Comment by singularity-s0** [comment]
需要找一个合适的 2-parameter hash function，最好使用现成或者自带的库函数完成，但目前还没有找到合适的dart和python通用的库。

> 一个简单的做法：将uis学号和密码发给后端，后端完成验证即可

此问题已被讨论过，为什么再次拿出来讨论？

**Comment by hasbai** [comment]
因为目前提议的方法存在安全隐患

**Comment by singularity-s0** [comment]
此问题之前也讨论过；传输至后端并不安全，后端可能被黑客植入后门截取所有凭据；按照隐私症状旦夕也不能把用户数据发送至非复旦的服务器；此外这样做还可能触发UIS风控

之前已全部讨论过这些问题，再次重复讨论没有意义。

**Comment by hasbai** [comment]
我这个提议确实存在问题，但是目前apikey的方法也不安全。
现在只能等待能否获得学校的oauth，在找到更好的认证方式之前，正式版将不能上线运行
