### ISSUE TITLE
查看编辑历史API

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#55]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
需要一个API，以查看某floor的编辑历史。
可以局限于管理员可用，也可以开放给所有用户使用，建议后者。

同时，floor应增加一个标记代表该帖是否曾被编辑过。

**Describe alternatives you've considered**
无

**Comment by hasbai** [comment]
Floor 对象会带有一个 history 字段

**Comment by singularity-s0** [comment]
<img width="460" alt="image" src="https://user-images.githubusercontent.com/12184989/145708188-434890f3-fbb5-4888-9c38-5448ef5b18d1.png">
1. altered_by 应返回是管理员修改还是用户自己修改，而不是user id
2. 如果为管理员删除，不应该返回 history
