### ISSUE TITLE
Penalty API应接受floor id而非user id

### ISSUE THREAD

**Issue by dest1n1s** [OpenTreeHole/backend#56]
前端无法从floor得到发送者的user id，故无法按照原有api发送penalty请求。

另外，处理举报时建议接受penalty等级，而非直接接受silent。

**Comment by singularity-s0** [comment]
1已实现，目前接受floor_id

**Comment by dest1n1s** [comment]
> 1已实现，目前接受floor_id

我是指应该只接受penalty_level和floor_id两个参数

**Comment by singularity-s0** [comment]
现在接受3个参数，floor_id, penalty_level 和 division_id

**Comment by singularity-s0** [comment]
详见Postman API文档

**Comment by dest1n1s** [comment]
> 现在接受3个参数，floor_id, penalty_level 和 division_id

所以为何需要division_id呢？前端从floor得到division_id较为困难

**Comment by hasbai** [comment]
floor里可以获得user id吗？我也认为division id没有必要
