### ISSUE TITLE
移动端推送通知

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#6]
- [x] 支持iOS端APNS推送
- [x] 支持Android端MiPush（具体待定）

**Comment by kavinzhao** [comment]
MiPush建议由Android前端开发者负责

**Comment by hasbai** [comment]
那你自行分配即可

**Comment by kavinzhao** [comment]
APNS流程简介：

1. **App请求通知权限，用户同意后从OS获取APNS token**
- 每个设备对应一个单独的token，可能会变化
2. **App将token上传树洞服务器**
- 树洞服务器保存每个用户的APNS token，作为User的一个字段（等待#11）
- 注意用户可能有不止一个设备，所以每个用户可能对应多个token
3. **需要发送通知时，树洞服务器向APNS服务器发送POST请求**
- APNS服务器使用证书或动态auth token（二选一）鉴权
- 通过APNS token来识别接收通知的目标设备
- 此步骤使用apns2 package完成
- （等待#4）

**Comment by kavinzhao** [comment]
APNS功能已完成；Sandbox测试通过
