### ISSUE TITLE
用户回复帖子时不应该给回复者本人发推送通知

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#62]

**Comment by singularity-s0** [comment]
此外，举报通知格式有误，应为##floor_id 而不是 ##内容

**Comment by hasbai** [comment]
没有给回复者本人发通知啊
![image](https://user-images.githubusercontent.com/34417826/149276691-b5097f74-311b-491d-bdb7-771018f487a6.png)

**Comment by singularity-s0** [comment]
不好意思描述不够具体；当用户关注了某帖子，并在此帖后回复，会收到自己回复的通知
