### ISSUE TITLE
删除推送通知token的API

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#66]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
需要一个API以在用户退出登录时删除push token

**Comment by hasbai** [comment]
目前的API设计不是很规范，如果按照REST规范的话，应当使用一张新的数据表存放用户的推送token，并提供完整的增删改查API。如果要图省事，把token放到用户的config下即可，调用PUT方法即可实现推送token的增删改查。

**Comment by singularity-s0** [comment]
既然这样，应尽量在上线前将API设计为最优版本，否则上线后将难以修改。

**Comment by hasbai** [comment]
你觉得这两种方案哪个好一些

**Comment by singularity-s0** [comment]
前者。此数据经常需要读取，放置在单独表内可以提高性能。
