### ISSUE TITLE
爬虫和DDOS防御

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#7]
对某一IP或某一用户短时间内大量请求；或载入时间非常早的帖子的请求进行人机验证

可以考虑ReCAPTCHA等第三方服务

**Comment by hasbai** [comment]
这两个要分开了说
ddos其实是防不住的，因为它就是纯粹的流量的对耗，如果真的有人要攻击的话我们一点办法都没有
这种论坛性质的应用其实我觉得没有必要反爬，别人爬这个我觉得没有什么负面影响，而且验证码会极大程度影响用户体验

**Comment by kavinzhao** [comment]
虽然不能完全防范，但至少最基本的防御要做，要不然所有数据被爬下来公布到网上很可能会出问题。

参考 T大树洞具备[DDOS防御能力](https://github.com/treehollow/install-doc#必须采取的安全措施请务必确保时刻没有子域名dns解析到服务器真实ip并且服务器真实ip必须始终保密) 和 [反爬机制](https://github.com/treehollow/install-doc#第六步注册google-recaptcha)

**Comment by kavinzhao** [comment]
可以看看[这个项目](https://github.com/fjcaetano/ReCaptcha)
