### ISSUE TITLE
后悔药

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#9]
根据树洞用户需求，可以考虑添加一种删除或修改自己的言论的机制，但

- 不应随意修改，即修改应当付出一定代价，例如短时禁言（改错别字除外）
- 保留修改记录

**Comment by hasbai** [comment]
这个功能已经实现了，[api](https://yapi.smart-xwork.cn/project/74677/interface/api/1128421)，也能保存历史记录
但是短时禁言这个功能，怎么判断他是不是在改错别字？如果要管理员人工判断的话太过麻烦，因此我觉得没有必要加这个限制

**Comment by kavinzhao** [comment]
可以考虑发帖后两分钟内可以任意修改，之后再修改或删除就要短时禁言

**Comment by hasbai** [comment]
我认为用户拥有其所撰写帖子的著作权，因此用户拥有**任意**修改帖子的权利
