### ISSUE TITLE
Floor增加字段，表明它是Hole的第几层楼

### ISSUE THREAD

**Issue by singularity-s0** [OpenTreeHole/backend#92]
**Which feature would you want to enhance, and why?**

Floor增加新的字段，表明它是Parent Hole的第几层楼。此字段有助于前端 **在通过推送通知和搜索结果定位楼层时** 提前确定需要加载哪个位置的floor。（即提前确定参数start_floor和length）

目前的实现会从头加载floor，反复调用加载API直到加载到所要定位的floor为止。性能较低。

此外，还可以提高 mention by hole 功能的缓存性能。目前 mention by hole 无法缓存，因为不知道hole的第一层floor是哪个，加入此字段后将使得这种缓存成为可能。

**Comment by JingYiJun** [comment]
新版本提供了floor.ranking字段表示在当前洞中的第几层
