### ISSUE TITLE
有概率无法登录（返回404）

### ISSUE THREAD

**Issue by KYLN24** [OpenTreeHole/backend#98]
**Describe the bug**
在树洞前端正常登录账号，密码无误，/api/login 返回 404

**To Reproduce**
1. 访问 www.fduhole.com/#/login 登陆页面
2. 使用该用户的邮箱进行登录
3. 服务器返回 404

**Expected behavior (Optional)**
正常登录。

**Screenshots (Optional)**
![](https://user-images.githubusercontent.com/54014142/154990670-c04e527b-7854-4587-b6fa-ae1cafb5e376.jpeg)

**Version**
用户无法获知后端版本号，请修改 issue 模板。

**Additional context**
来自用户邮件反馈。

该用户声称可成功修改密码，但始终无法登录。

暂不可确定是否是前端的问题。请检查日志。

**Comment by KYLN24** [comment]
![image](https://user-images.githubusercontent.com/54014142/154990670-c04e527b-7854-4587-b6fa-ae1cafb5e376.jpeg)

**Comment by hasbai** [comment]
无法复现，这是偶然情况还是这个用户一直如此？404应该是账号不存在，如果一直如此的话他的账号可能不存在。
另：请按照 issue 模板提出 issue

**Comment by KYLN24** [comment]
该用户声称一直如此，并声称可以正常修改密码。

**Comment by hasbai** [comment]
建议让他重新注册

**Comment by KYLN24** [comment]
该用户称已解决
